---
kind: pipeline
type: docker
name: test

steps:
  - name: test
    image: rust:1.38.0
    commands:
      - scripts/test
      - apt-get install -y libssl-dev
      - cargo install wasm-pack
      - scripts/generate
  - name: deploy
    image: node:12.12-alpine
    environment:
      FIREBASE_TOKEN:
        from_secret: FIREBASE_TOKEN
    commands:
      - yarn global add firebase-tools
      - /bin/ash /drone/src/scripts/deploy --token "$FIREBASE_TOKEN"
    when:
      branch:
        - master
trigger:
  ref:
    include:
      - refs/heads/**
  event:
    - push
