[package]
name = "adonais_core"
version = "0.1.0"
authors = ["Tom Milligan <code@tommilligan.net>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.9", features = ["wasmbind"] }
chrono-tz = "0.5.1"
serde = "1.0.101"
serde_derive = "1.0.101"
serde_json = "1.0.40"
wasm-bindgen = "0.2.51"

[lib]
crate-type = ["lib", "cdylib"]
