#!/bin/bash
# Generate wasm files from rust library and add them to the js codebase

set -ex

cargo test --manifest-path sync/adonais_core/Cargo.toml
cargo test --manifest-path sync/adonais_core/Cargo.toml --no-default-features --features parser_pest
